<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find fishbot_description)/urdf/fish_bot/common_intertia.xacro" />
    <xacro:macro name="base_xacro" params="length radius">        
        <link name="base_footprint">
            
        </link>

        <link name="base_link">
            <visual>

                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>

                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>

                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>

                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>

                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>

            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}" />
        </link>

        <joint name="joint_name" type="fixed">
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <axis xyz="0.0 0.0 0.0"/>
            <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
        </joint>
        </xacro:macro>
</robot>