controller_manager:
  ros__parameters:
    update_rate: 100 
    use_sim_time: true  

    rprobot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    rprobot_effort_controller:
      type: effort_controllers/JointGroupEffortController
    rprobot_mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController


rprobot_effort_controller:
  ros__parameters:
    reference_timeout: 0.9

    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

rprobot_mecanum_drive_controller:
  ros__parameters:
    reference_timeout: 0.9

    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "back_right_wheel_joint"
    rear_left_wheel_command_joint_name: "back_left_wheel_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.45

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    use_stamped_vel: false
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]